# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple"]

TYPE_CHECKING = False
VERSION_TUPLE = tuple[int | str, ...] if TYPE_CHECKING else object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = '0.0.post1.dev21+gdf7539c.d20250225'
__version_tuple__ = version_tuple = (0, 0, 'dev21', 'gdf7539c.d20250225')
