name: Datamimic Performance Reporting Tool CI/CD
run-name: ${{ github.actor || 'unknown' }} is running ${{ github.workflow || 'workflow' }} on ${{ github.repository || 'repo' }}
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - "*"

env:
  RUNTIME_ENVIRONMENT: production

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Export latest tag
        run: |
          # Get the last tag and ensure it's a version number
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          if [[ ! $LATEST_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Warning: Latest tag $LATEST_TAG is not in version format (x.y.z), using 0.0.0"
            LATEST_TAG="0.0.0"
          fi
          echo "DATAMIMIC_PERF_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "DATAMIMIC_PERF_LATEST_TAG=$LATEST_TAG" >> build.env
          
      - name: Export lib version without patch
        run: |
          export LIB_VERSION_WITHOUT_PATCH=$(echo "$DATAMIMIC_PERF_LATEST_TAG" | sed 's/\.[^.]*$//')
          echo "LIB_VERSION_WITHOUT_PATCH=$LIB_VERSION_WITHOUT_PATCH" >> $GITHUB_ENV
          echo "LIB_VERSION_WITHOUT_PATCH=$LIB_VERSION_WITHOUT_PATCH" >> build.env
          
      - name: Upload build.env
        uses: actions/upload-artifact@v4
        with:
          name: setup
          path: build.env
          if-no-files-found: error
          retention-days: 1

  install_dependencies:
    runs-on: ubuntu-22.04
    container: python:3.11-slim-buster
    needs: setup
    permissions:
      contents: read
    steps:
      - name: Install dependencies os packages
        run: |
          apt-get update
          apt-get install -y build-essential git
          pip install uv
          git config --global --add safe.directory $(realpath .)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Cache python venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('./pyproject.toml') }}
      - name: Check version
        run: |
          uv --version
        shell: bash
      - name: Create virtual env
        run: |
          uv venv .venv --python 3.11
          . .venv/bin/activate
      - name: Install dependencies
        run: |
          uv sync --all-extras
        shell: bash

  lint:
    runs-on: ubuntu-22.04
    needs: install_dependencies
    container: python:3.11-slim-buster
    steps:
      - name: Setup git
        run: |
          apt-get update
          apt-get install -y git
          git config --global --add safe.directory $(realpath .)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Load venv cache
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('./pyproject.toml') }}
      - name: Run mypy
        run: |
          . .venv/bin/activate
          uv run mypy app
        shell: bash
      - name: Run ruff
        run: |
          . .venv/bin/activate
          uv run ruff check app
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv Package Manager
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv sync
        shell: bash

      - name: Build Package
        run: |
          uv build
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*

  unit_test:
    runs-on: ubuntu-22.04
    needs: install_dependencies
    container: python:3.11-slim-buster
    steps:
      - name: Setup git
        run: |
          apt-get update
          apt-get install -y git
          git config --global --add safe.directory $(realpath .)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Load venv cache
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('./pyproject.toml') }}
      - name: Run unit tests with coverage
        run: |
          . .venv/bin/activate
          uv run pytest tests/ -n 2 --cov=app --cov-report=xml
        shell: bash
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage.xml

  sonarcloud_analysis:
    runs-on: ubuntu-22.04
    needs: [ unit_test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage-reports

      - name: Move coverage reports
        run: |
          mv coverage-reports/coverage-unit/coverage.xml coverage-reports/coverage-unit.xml
          rm -rf coverage-reports/coverage-unit
          rm -rf coverage-reports/artifact
          rm -rf coverage-reports/setup

        shell: bash

      - name: Display structure of downloaded files
        run: ls -R coverage-reports

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish_dev:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-22.04
    needs: [ unit_test ]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/datamimic-perf
    permissions:
      id-token: write # Mandatory for trusted publishing
      contents: read
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare Distribution Files
        run: |
          mkdir -p dist_files
          mv dist/artifact/*.whl dist_files
          mv dist/artifact/*.tar.gz dist_files
          rm -rf dist
          mv dist_files dist

      - name: List Distribution Files
        run: ls -la dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: [ unit_test ]
    environment:
      name: pypi
      url: https://pypi.org/p/datamimic-perf
    permissions:
      id-token: write # Mandatory for trusted publishing
      contents: read
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare Distribution Files
        run: |
          mkdir -p dist_files
          mv dist/artifact/*.whl dist_files
          mv dist/artifact/*.tar.gz dist_files
          rm -rf dist
          mv dist_files dist

      - name: List Distribution Files
        run: ls -la dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 
